In [2]:
import pandas as pd
import numpy as np

In [3]:
Lifecycle_Retention=pd.read_excel(r"../hire_to_retire_analytics.xlsx",sheet_name="Lifecycle_Retention")
Lifecycle_Retention.head()

,Employee_ID,Employment_Status,Hire_Date,Termination_Date,Total_Tenure_Months,Comp_vs_Market,Final_Salary,Avg_KPI_Career,Promotion_Count,Last_Promotion_Date,Exit_Reason,Attrition_Risk_Score
0,EMP_000001,Terminated,2018-01-01,2021-03-02,38,-0.0411,119000,0.7242,0,NaT,Voluntary_Personal,49.6
1,EMP_000002,Terminated,2018-01-01,2019-01-31,13,-0.1323,138000,0.6864,0,NaT,Involuntary_Restructure,54.9
2,EMP_000003,Terminated,2018-01-01,2023-01-31,61,0.0696,126000,0.6756,0,NaT,Voluntary_Personal,51.9
3,EMP_000004,Terminated,2018-01-01,2018-07-02,6,-0.1148,141000,0.4287,0,NaT,Voluntary_Low_Engagement,71.8
4,EMP_000005,Terminated,2018-01-01,2020-09-01,32,0.1071,116000,0.6556,0,NaT,Voluntary_Low_Engagement,53.4

In [4]:
Lifecycle_Retention_new=Lifecycle_Retention.copy()

In [5]:
Lifecycle_Retention_new.info()

<class 'pandas.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Employee_ID           25000 non-null  str
 1   Employment_Status     25000 non-null  str
 2   Hire_Date             25000 non-null  datetime64[us]
 3   Termination_Date      14592 non-null  datetime64[us]
 4   Total_Tenure_Months   25000 non-null  int64
 5   Comp_vs_Market        25000 non-null  float64
 6   Final_Salary          25000 non-null  int64
 7   Avg_KPI_Career        24050 non-null  float64
 8   Promotion_Count       25000 non-null  int64
 9   Last_Promotion_Date   1542 non-null   datetime64[us]
 10  Exit_Reason           14592 non-null  str
 11  Attrition_Risk_Score  25000 non-null  float64
dtypes: datetime64[us](3), float64(3), int64(3), str(3)
memory usage: 2.3 MB

In [6]:
Lifecycle_Retention_new.describe()

,Hire_Date,Termination_Date,Total_Tenure_Months,Comp_vs_Market,Final_Salary,Avg_KPI_Career,Promotion_Count,Last_Promotion_Date,Attrition_Risk_Score
count,25000,14592,25000.000000,25000.000000,25000.000000,24050.000000,25000.000000,1542,25000.000000
mean,2021-09-09 17:14:47.040000,2022-07-17 21:54:46.184210,22.286360,0.060330,128755.920000,0.706772,0.079040,2023-02-23 18:21:00.700389,53.749492
min,2018-01-01 00:00:00,2018-07-02 00:00:00,0.000000,-0.242700,74000.000000,0.273600,0.000000,2019-03-24 00:00:00,23.200000
25%,2020-02-12 00:00:00,2021-05-16 00:00:00,10.000000,-0.002100,105000.000000,0.632800,0.000000,2022-07-27 12:00:00,48.200000
50%,2021-11-01 00:00:00,2022-10-09 00:00:00,19.000000,0.058600,124000.000000,0.710400,0.000000,2023-12-02 00:00:00,53.900000
75%,2023-05-05 00:00:00,2023-11-18 00:00:00,31.000000,0.121225,150000.000000,0.783500,0.000000,2023-12-16 00:00:00,59.500000
max,2024-12-30 00:00:00,2024-11-29 00:00:00,83.000000,0.421400,301000.000000,1.000000,2.000000,2023-12-31 00:00:00,88.300000
std,NaN,NaN,15.799656,0.092963,29619.254497,0.106879,0.327898,NaN,8.295722

In [7]:
Lifecycle_Retention_new.shape

(25000, 12)

In [8]:
Lifecycle_Retention_new.isnull().sum()

Employee_ID                 0
Employment_Status           0
Hire_Date                   0
Termination_Date        10408
Total_Tenure_Months         0
Comp_vs_Market              0
Final_Salary                0
Avg_KPI_Career            950
Promotion_Count             0
Last_Promotion_Date     23458
Exit_Reason             10408
Attrition_Risk_Score        0
dtype: int64

In [9]:
Lifecycle_Retention_new["Exit_Reason"]=Lifecycle_Retention_new['Exit_Reason'].fillna("Still Active")

In [10]:
Lifecycle_Retention_new["Termination_Date"]=Lifecycle_Retention_new['Termination_Date'].fillna(0)

In [11]:
Lifecycle_Retention_new["Last_Promotion_Date"]=Lifecycle_Retention_new['Last_Promotion_Date'].fillna(0)

In [12]:
Lifecycle_Retention_new["Avg_KPI_Career"]=Lifecycle_Retention_new['Avg_KPI_Career'].fillna(Lifecycle_Retention_new['Avg_KPI_Career'].median())

In [13]:
Lifecycle_Retention_new.isnull().sum()

Employee_ID             0
Employment_Status       0
Hire_Date               0
Termination_Date        0
Total_Tenure_Months     0
Comp_vs_Market          0
Final_Salary            0
Avg_KPI_Career          0
Promotion_Count         0
Last_Promotion_Date     0
Exit_Reason             0
Attrition_Risk_Score    0
dtype: int64

In [14]:
Lifecycle_Retention_new.duplicated().sum()

np.int64(0)

In [15]:
for col in Lifecycle_Retention_new.columns:
    if Lifecycle_Retention_new[col].dtype=="object":
        Lifecycle_Retention_new[col]=Lifecycle_Retention_new[col].astype("string")

In [16]:
Lifecycle_Retention_new["Termination_Date"]=pd.to_datetime(Lifecycle_Retention_new["Termination_Date"],errors="coerce")

In [17]:
Lifecycle_Retention_new["Last_Promotion_Date"]=pd.to_datetime(Lifecycle_Retention_new["Last_Promotion_Date"],errors="coerce")

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_4612\94523031.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  Lifecycle_Retention_new["Last_Promotion_Date"]=pd.to_datetime(Lifecycle_Retention_new["Last_Promotion_Date"],errors="coerce")

In [18]:
Lifecycle_Retention_new.info()

<class 'pandas.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Employee_ID           25000 non-null  str
 1   Employment_Status     25000 non-null  str
 2   Hire_Date             25000 non-null  datetime64[us]
 3   Termination_Date      14592 non-null  datetime64[us]
 4   Total_Tenure_Months   25000 non-null  int64
 5   Comp_vs_Market        25000 non-null  float64
 6   Final_Salary          25000 non-null  int64
 7   Avg_KPI_Career        25000 non-null  float64
 8   Promotion_Count       25000 non-null  int64
 9   Last_Promotion_Date   1542 non-null   datetime64[us]
 10  Exit_Reason           25000 non-null  str
 11  Attrition_Risk_Score  25000 non-null  float64
dtypes: datetime64[us](3), float64(3), int64(3), str(3)
memory usage: 2.3 MB

In [19]:
Lifecycle_Retention_new.to_csv("../CleanedCSVs/Lifecycle_Retention_new.csv",index=False)