In [2]:
import pandas as pd
import numpy as np

In [3]:
Monthly_Pulse_Timeseries=pd.read_excel(r"../hire_to_retire_analytics.xlsx",sheet_name="Monthly_Pulse_Timeseries")
Monthly_Pulse_Timeseries.head()

,Employee_ID,Year_Month,Pulse_Date,Month_Number,Monthly_Pulse_Score,Culture_Band
0,EMP_000001,2018-01,2018-01-31,1,83.9,High
1,EMP_000001,2018-03,2018-03-02,2,75.7,High
2,EMP_000001,2018-04,2018-04-01,3,81.1,High
3,EMP_000001,2018-05,2018-05-01,4,84.7,High
4,EMP_000001,2018-05,2018-05-31,5,78.7,High

In [4]:
Monthly_Pulse_Timeseries_new=Monthly_Pulse_Timeseries.copy()

In [5]:
Monthly_Pulse_Timeseries_new.info()

<class 'pandas.DataFrame'>
RangeIndex: 557168 entries, 0 to 557167
Data columns (total 6 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Employee_ID          557168 non-null  str
 1   Year_Month           557168 non-null  str
 2   Pulse_Date           557168 non-null  datetime64[us]
 3   Month_Number         557168 non-null  int64
 4   Monthly_Pulse_Score  557168 non-null  float64
 5   Culture_Band         557168 non-null  str
dtypes: datetime64[us](1), float64(1), int64(1), str(3)
memory usage: 25.5 MB

In [6]:
Monthly_Pulse_Timeseries_new.describe()

                       Pulse_Date   Month_Number  Monthly_Pulse_Score
count                      557168  557168.000000        557168.000000
mean   2022-05-18 01:40:41.524280      17.243185            70.339970
min           2018-01-31 00:00:00       1.000000             0.000000
25%           2021-02-11 00:00:00       6.000000            63.700000
50%           2022-08-07 00:00:00      14.000000            70.900000
75%           2023-10-27 00:00:00      25.000000            77.400000
max           2024-12-31 00:00:00      83.000000           100.000000
std                           NaN      13.984597            10.180054

In [7]:
Monthly_Pulse_Timeseries_new.shape

(557168, 6)

In [8]:
Monthly_Pulse_Timeseries_new.isnull().sum()

Employee_ID            0
Year_Month             0
Pulse_Date             0
Month_Number           0
Monthly_Pulse_Score    0
Culture_Band           0
dtype: int64

In [9]:
Monthly_Pulse_Timeseries_new.duplicated().sum()

np.int64(0)

In [10]:
for col in Monthly_Pulse_Timeseries_new.columns:
    if Monthly_Pulse_Timeseries_new[col].dtype=="object":
        Monthly_Pulse_Timeseries_new[col]=Monthly_Pulse_Timeseries_new[col].astype("string")

In [11]:
Monthly_Pulse_Timeseries_new.info()

<class 'pandas.DataFrame'>
RangeIndex: 557168 entries, 0 to 557167
Data columns (total 6 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Employee_ID          557168 non-null  str
 1   Year_Month           557168 non-null  str
 2   Pulse_Date           557168 non-null  datetime64[us]
 3   Month_Number         557168 non-null  int64
 4   Monthly_Pulse_Score  557168 non-null  float64
 5   Culture_Band         557168 non-null  str
dtypes: datetime64[us](1), float64(1), int64(1), str(3)
memory usage: 25.5 MB

In [12]:
Monthly_Pulse_Timeseries_new.to_csv("../CleanedCSVs/Monthly_Pulse_Timeseries_new.csv",index=False)