In [2]:
import pandas as pd
import numpy as np

In [3]:
Performance_Timeseries=pd.read_excel(r"../hire_to_retire_analytics.xlsx",sheet_name="Performance_Timeseries")
Performance_Timeseries.head()

,Employee_ID,Quarter_Label,Quarter_Number,Quarter_Date,Tenure_Quarters,KPI_Achievement,Quality_of_Work,Skill_Acquisition_Score
0,EMP_000001,2018Q2,1,2018-04-02,1,0.4973,0.8318,0.5554
1,EMP_000001,2018Q3,2,2018-07-02,2,0.7180,0.6559,0.5569
2,EMP_000001,2018Q4,3,2018-10-01,3,0.8357,0.7053,0.6309
3,EMP_000001,2018Q4,4,2018-12-31,4,0.9101,0.7942,0.5782
4,EMP_000001,2019Q2,5,2019-04-01,5,0.5367,0.6769,0.5831

In [4]:
Performance_Timeseries_new=Performance_Timeseries.copy()

In [5]:
Performance_Timeseries_new.info()

<class 'pandas.DataFrame'>
RangeIndex: 178124 entries, 0 to 178123
Data columns (total 8 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Employee_ID              178124 non-null  str
 1   Quarter_Label            178124 non-null  str
 2   Quarter_Number           178124 non-null  int64
 3   Quarter_Date             178124 non-null  datetime64[us]
 4   Tenure_Quarters          178124 non-null  int64
 5   KPI_Achievement          178124 non-null  float64
 6   Quality_of_Work          178124 non-null  float64
 7   Skill_Acquisition_Score  178124 non-null  float64
dtypes: datetime64[us](1), float64(3), int64(2), str(2)
memory usage: 10.9 MB

In [6]:
Performance_Timeseries_new.describe()

,Quarter_Number,Quarter_Date,Tenure_Quarters,KPI_Achievement,Quality_of_Work,Skill_Acquisition_Score
count,178124.000000,178124,178124.000000,178124.000000,178124.000000,178124.000000
mean,5.993168,2022-06-03 13:01:56.494127,5.993168,0.726305,0.687198,0.652784
min,1.000000,2018-04-02 00:00:00,1.000000,0.199900,0.245500,0.247600
25%,2.000000,2021-03-03 00:00:00,2.000000,0.640500,0.618400,0.588600
50%,5.000000,2022-08-24 00:00:00,5.000000,0.728300,0.687900,0.651800
75%,8.000000,2023-11-08 00:00:00,8.000000,0.814700,0.756400,0.716200
max,27.000000,2024-12-30 00:00:00,27.000000,1.000000,1.000000,1.000000
std,4.608815,NaN,4.608815,0.126246,0.101238,0.094670

In [7]:
Performance_Timeseries_new.shape

(178124, 8)

In [8]:
Performance_Timeseries_new.isnull().sum()

Employee_ID                0
Quarter_Label              0
Quarter_Number             0
Quarter_Date               0
Tenure_Quarters            0
KPI_Achievement            0
Quality_of_Work            0
Skill_Acquisition_Score    0
dtype: int64

In [9]:
Performance_Timeseries_new.duplicated().sum()

np.int64(0)

In [10]:
for col in Performance_Timeseries_new.columns:
    if Performance_Timeseries_new[col].dtype=="object":
        Performance_Timeseries_new[col]=Performance_Timeseries_new[col].astype("string")

In [11]:
Performance_Timeseries_new.info()

<class 'pandas.DataFrame'>
RangeIndex: 178124 entries, 0 to 178123
Data columns (total 8 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Employee_ID              178124 non-null  str
 1   Quarter_Label            178124 non-null  str
 2   Quarter_Number           178124 non-null  int64
 3   Quarter_Date             178124 non-null  datetime64[us]
 4   Tenure_Quarters          178124 non-null  int64
 5   KPI_Achievement          178124 non-null  float64
 6   Quality_of_Work          178124 non-null  float64
 7   Skill_Acquisition_Score  178124 non-null  float64
dtypes: datetime64[us](1), float64(3), int64(2), str(2)
memory usage: 10.9 MB

In [12]:
Performance_Timeseries_new.to_csv("../CleanedCSVs/Performance_Timeseries_new.csv",index=False)